apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: msagi-capstone-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msagi-capstone-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10