apiVersion: v1
kind: Service
metadata:
  name: msagi-capstone-app
spec:
  type: NodePort
  selector:
    app: msagi-capstone-app
  ports:
    - protocol: TCP
      nodePort: 31000 # The port on each node on which this service is exposed when type is NodePort or LoadBalancer.
      port: 8000  # The port that will be exposed by this service.
      targetPort: 8080  # Number or name of the port to access on the pods targeted by the service.