apiVersion: v1
kind: Service
metadata:
  name: msagi-capstone-app
spec:
  type: LoadBalancer
  selector:
    app: msagi-capstone-app
  ports:
    - protocol: TCP
      port: 8080  # The port that will be exposed by this service.
      targetPort: 8080  # Number or name of the port to access on the pods targeted by the service.