version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-test: 
    docker:
      - image: msaginwm/devsecops-base:2023.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd application
            make install
      - save_cache:
          paths:
              - .venv
          key: v3-dependencies-{{ checksum "application/requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            cd application
            make lint

  static-application-security-testing:
    docker:
      - image: msaginwm/devsecops-base:2023.04
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v3-dependencies-{{ checksum "application/requirements.txt" }}
      - run:
          name: Run SAST
          command: |
            . .venv/bin/activate
            cd application
            make sast

  deploy-infrastructure:
    docker:
      - image: msaginwm/devsecops-base:2023.04
    steps:
      - checkout
      - run:
          name: Deploy infrastructure
          no_output_timeout: 30m
          command: |
            cd infrastructure
            ./deploy-infrastructure.sh

  deploy-workload:
    docker:
      - image: msaginwm/devsecops-base:2023.04
    steps:
      - checkout
      - run:
          name: Create kubeconfig
          command: |
            aws eks --region us-east-1 update-kubeconfig --name msagi-eks-cluster
      - run:
          name: Deploy Workload
          command: |
            kubectl get pods --all-namespaces
            cd application
            make deploy
  
  smoke-test:
    docker:
      - image: msaginwm/devsecops-base:2023.04
    steps:
      - checkout
      - run:
          name: Create kubeconfig
          command: |
            aws eks --region us-east-1 update-kubeconfig --name msagi-eks-cluster
      - run:
          name: Smoke test - health check 
          command: |
            cd application
            make smoketest

workflows:
  default:
    jobs:
      - build-and-test
      - static-application-security-testing:
          requires: [build-and-test]
      - docker/publish:
          requires: [static-application-security-testing]
          path: application
          docker-context: application
          image: msaginwm/msagi-capstone
          tag: v1.0.1
      - deploy-infrastructure:
          requires: [docker/publish]
#          filters:
#            branches:
#              only: [infra-branch]
      - deploy-workload:
          requires: [deploy-infrastructure]
      - smoke-test:
         requires: [deploy-workload]
