version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-test: 
    docker:
      - image: python:3.11.3-alpine3.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache build-base=0.5-r3 linux-headers=5.19.5-r0 make=4.3-r1
            python3 -m venv .venv
            . .venv/bin/activate
            cd application
            make install
      - save_cache:
          paths:
              - .venv
          key: v1-dependencies-{{ checksum "application/requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            cd application
            make lint

  static-application-security-testing:
    docker:
      - image: python:3.11.3-alpine3.17
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "application/requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache build-base=0.5-r3 linux-headers=5.19.5-r0 make=4.3-r1
      - run:
          name: Run SAST
          command: |
            . .venv/bin/activate
            cd application
            make sast

workflows:
  default:
    jobs:
      - build-and-test
      - static-application-security-testing:
          requires: [build-and-test]
      - docker/publish:
          requires: [static-application-security-testing]
          path: application
          image: msaginwm/msagi-capstone
          tag: v1.0.1
#      - deploy-infrastructure:
#          requires: [build-docker-image]
#          filters:
#            branches:
#              only: [infra-branch]
#      - configure-infrastructure:
#          requires: [deploy-infrastructure]
#      - deploy-app:
#          requires: [configure-infrastructure]
#      - smoke-test:
#          requires: [deploy-backend, deploy-frontend]
#      - cloudfront-update:
#          requires: [smoke-test]
#      - cleanup:
#          requires: [cloudfront-update]